stages:
  - build
  - test
  - github

#  Templates

.job_template: &job
  tags:
    - docker-runner

.build_template: &build
  stage: build
  script:
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go get
    - go get .
    - go build

# Build stages

build alpine:
  <<: *job
  <<: *build
  image: golang:1.8-alpine

build linux:
  <<: *job
  <<: *build
  image: golang:1.8

push to github:
  <<: *job
  image: wurbanski/alpine-git
  stage: github
  script:
    - if [ ! -n "$(grep "^github.com " ~/.ssh/known_hosts)" ]; then ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null; fi
    - eval $(ssh-agent -s)
    - echo "$GITHUB_SSH_KEY" > /tmp/ssh_key && chmod 600 /tmp/ssh_key
    - ssh-add /tmp/ssh_key
    - git push $GITHUB_REPO_URL HEAD:master 
    - ssh-agent -k || { ssh-agent -k ; exit 1; }
  allow_failure: True
  only:
    - master